using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace db_tsh.Models
{
    public class Payment
    {
        public int PaymentNum { get; set; }  // Auto-generated by DB
        public int PolicyId { get; set; }    // Foreign key to Policy table
        public DateTime PDate { get; set; }
        public int PAmount { get; set; }
        public string VisaNumber { get; set; }

        // Navigation property
        public Policy Policy { get; set; }
    }
}
